remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
title: In-context learning in natural and artificial intelligence
description: Workshop COGSCI 2024 IN ROTTERDAM - July 24th 2024
show_downloads: false
