remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
title: In-context learning in natural and artificial intelligence
description: Workshop at CogSci 2024 (Rotterdam - July 24th 2024)
show_downloads: false
